// src/helpers/responseError.js

const ResponseError = {
  NO_ERROR: 'NO_ERROR',
  ERROR_100: 'ERROR_100', // 'User is not logged in.'
  ERROR_101: 'ERROR_101', // 'User does not have the right roles.'
  ERROR_102: 'ERROR_102', // 'Login or password is incorrect.'
  ERROR_103: 'ERROR_103', // 'User email address is not verified'
  ERROR_104: 'ERROR_104', // 'User phone number is not verified'
  ERROR_105: 'ERROR_105', // 'User account is not verified'
  ERROR_106: 'ERROR_106', // 'User already exists'
  ERROR_107: 'ERROR_107', // 'Please log in using socials'
  ERROR_108: 'ERROR_108', // 'User doesn\'t have Wallet'
  ERROR_109: 'ERROR_109', // 'Insufficient wallet balance'
  ERROR_110: 'ERROR_110', // 'Can\'t update this user role'
  ERROR_111: 'ERROR_111', // 'You can buy only :quantity products'
  ERROR_112: 'ERROR_112', // 'You can buy only :quantity products'
  ERROR_113: 'ERROR_113', // 'Deliveryman doesn\'t have Wallet'
  ERROR_114: 'ERROR_114', // 'Seller doesn\'t have Wallet'
  ERROR_115: 'ERROR_115', // 'Phone not found'
  ERROR_116: 'ERROR_116', // 'Ads already activated'
  ERROR_117: 'ERROR_117', // 'Phone is required'
  ERROR_118: 'ERROR_118', // 'Shop is closed'
  ERROR_119: 'ERROR_119', // 'Duplicate stock'

  ERROR_201: 'ERROR_201', // 'Wrong OTP Code'
  ERROR_202: 'ERROR_202', // 'Too many request, try later'
  ERROR_203: 'ERROR_203', // 'OTP code is expired'
  ERROR_204: 'ERROR_204', // 'You are not seller yet or your shop is not approved'
  ERROR_205: 'ERROR_205', // 'Shop already created'
  ERROR_206: 'ERROR_206', // 'User already has Shop'
  ERROR_207: 'ERROR_207', // 'Can\'t update Shop Seller'
  ERROR_208: 'ERROR_208', // 'Subscription already active'
  ERROR_209: 'ERROR_209', // 'Shop delivery zone already created'
  ERROR_210: 'ERROR_210', // 'Delivery already attached'
  ERROR_211: 'ERROR_211', // 'invalid deliveryman or token not found'
  ERROR_212: 'ERROR_212', // 'Not your shop. Check your other account'
  ERROR_213: 'ERROR_213', // 'Shop is parent'
  ERROR_214: 'ERROR_214', // 'Your subscription product limit has expired'
  ERROR_215: 'ERROR_215', // 'Incorrect code or token expired'
  ERROR_216: 'ERROR_216', // 'Verify code sent'
  ERROR_217: 'ERROR_217', // 'email code sent'
  ERROR_218: 'ERROR_218', // 'not activated'
  ERROR_219: 'ERROR_219', // 'Your subscription is expired at'
  ERROR_220: 'ERROR_220', // 'Your subscription product limit has expired'

  ERROR_249: 'ERROR_249',
  ERROR_250: 'ERROR_250',
  ERROR_251: 'ERROR_251',
  ERROR_252: 'ERROR_252',
  ERROR_253: 'ERROR_253',
  ERROR_254: 'ERROR_254',
  ERROR_255: 'ERROR_255',

  ERROR_400: 'ERROR_400',
  ERROR_401: 'ERROR_401',
  ERROR_403: 'ERROR_403',
  ERROR_404: 'ERROR_404',
  ERROR_415: 'ERROR_415',
  ERROR_422: 'ERROR_422',
  ERROR_429: 'ERROR_429',
  ERROR_430: 'ERROR_430',
  ERROR_431: 'ERROR_431',
  ERROR_432: 'ERROR_432',
  ERROR_433: 'ERROR_433',
  ERROR_434: 'ERROR_434',
  ERROR_435: 'ERROR_435',
  ERROR_436: 'ERROR_436',

  ERROR_501: 'ERROR_501',
  ERROR_502: 'ERROR_502',
  ERROR_503: 'ERROR_503',
  ERROR_504: 'ERROR_504',
  ERROR_505: 'ERROR_505',
  ERROR_506: 'ERROR_506',
  ERROR_507: 'ERROR_507',
  ERROR_508: 'ERROR_508',
  ERROR_509: 'ERROR_509',
  ERROR_510: 'ERROR_510',

  // Custom messages
  NEW_ORDER: 'NEW_ORDER',
  NEW_PARCEL_ORDER: 'NEW_PARCEL_ORDER',
  CONFIRMATION_CODE: 'CONFIRMATION_CODE',
  PHONE_OR_EMAIL_NOT_FOUND: 'PHONE_OR_EMAIL_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  ORDER_POINT: 'ORDER_POINT',
  SHOP_NOT_FOUND: 'SHOP_NOT_FOUND',
  OTHER_SHOP: 'OTHER_SHOP',
  NOT_IN_POLYGON: 'NOT_IN_POLYGON',
  CURRENCY_NOT_FOUND: 'CURRENCY_NOT_FOUND',
  LANGUAGE_NOT_FOUND: 'LANGUAGE_NOT_FOUND',
  CANT_DELETE_ORDERS: 'CANT_DELETE_ORDERS',
  CANT_UPDATE_ORDERS: 'CANT_UPDATE_ORDERS',
  STATUS_CHANGED: 'STATUS_CHANGED',
  SHOP_STATUS_CHANGED: 'SHOP_STATUS_CHANGED',
  ADD_CASHBACK: 'ADD_CASHBACK',
  WALLET_TOP_UP: 'WALLET_TOP_UP',
  VIA_WALLET: 'VIA_WALLET',
  WALLET_WITHDRAW: 'WALLET_WITHDRAW',
  PAYOUT_ACCEPTED: 'PAYOUT_ACCEPTED',
  CANT_DELETE_IDS: 'CANT_DELETE_IDS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_IS_BANNED: 'USER_IS_BANNED',
  INCORRECT_LOGIN_PROVIDER: 'INCORRECT_LOGIN_PROVIDER',
  FIN_FO: 'FIN_FO',
  USER_SUCCESSFULLY_REGISTERED: 'USER_SUCCESSFULLY_REGISTERED',
  USER_CARTS_IS_EMPTY: 'USER_CARTS_IS_EMPTY',
  PRODUCTS_IS_EMPTY: 'PRODUCTS_IS_EMPTY',
  RECORD_WAS_SUCCESSFULLY_CREATED: 'RECORD_WAS_SUCCESSFULLY_CREATED',
  RECORD_WAS_SUCCESSFULLY_UPDATED: 'RECORD_WAS_SUCCESSFULLY_UPDATED',
  RECORD_WAS_SUCCESSFULLY_DELETED: 'RECORD_WAS_SUCCESSFULLY_DELETED',
  IMAGE_SUCCESSFULLY_UPLOADED: 'IMAGE_SUCCESSFULLY_UPLOADED',
  EMPTY_STATUS: 'EMPTY_STATUS',
  SUCCESS: 'SUCCESS',
  DELIVERYMAN_IS_NOT_CHANGED: 'DELIVERYMAN_IS_NOT_CHANGED',
  CATEGORY_IS_PARENT: 'CATEGORY_IS_PARENT',
  TYPE_PRICE_USER: 'TYPE_PRICE_USER',
  NOTHING_TO_UPDATE: 'NOTHING_TO_UPDATE',
  EMPTY: 'EMPTY',
  ORDER_OR_DELIVERYMAN_IS_EMPTY: 'ORDER_OR_DELIVERYMAN_IS_EMPTY',
  DELIVERYMAN_SETTING_EMPTY: 'DELIVERYMAN_SETTING_EMPTY',
  NOT_IN_PARCEL_POLYGON: 'NOT_IN_PARCEL_POLYGON',
  CANT_UPDATE_EMPTY_ORDER: 'CANT_CREATE_OR_UPDATE_EMPTY_ORDER',
  REPLACE_PRODUCT: 'REPLACE_PRODUCT',

  // Labels
  TAX: 'TAX',
  DATE: 'DATE',
  FROM: 'FROM',
  PRICE: 'PRICE',
  ORDER: 'ORDER',
  NUMBER: 'NUMBER',
  COUPON: 'COUPON',
  DETAILS: 'DETAILS',
  PRODUCT: 'PRODUCT',
  INVOICE: 'INVOICE',
  DISCOUNT: 'DISCOUNT',
  QUANTITY: 'QUANTITY',
  TOTAL_TAX: 'TOTAL_TAX',
  TOTAL_PRICE: 'TOTAL_PRICE',
  SERVICE_FEE: 'SERVICE_FEE',
  ADDRESS_PLACE: 'ADDRESS_PLACE',
  DELIVERY_FEE: 'DELIVERY_FEE',
  PRICE_WITHOUT_TAX: 'PRICE_WITHOUT_TAX',
  DELIVERY_DATE_TIME: 'DELIVERY_DATE_TIME',
  TOTAL_PRICE_WITHOUT_TAX: 'TOTAL_PRICE_WITHOUT_TAX',
};

module.exports = { ResponseError };
